version: '3'
services:
        web_t8:
                image: flask_team_cheese_t8_v1
                build: .
                ports:
                        - "8071:8080"
                volumes:
                        - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/P3T8_ezkg/volumes
